### ISSUE TITLE
Can it be compiled on windows10?

### ISSUE THREAD

**Issue by Zjek** [SychevS/p2p#1]
Hello!

I have found your project and wanna give a try.How to compile in Windows system？

Thanks！

**Comment by SychevS** [comment]
Hello, @Zjek ! Yes, it can be compiled on windows 10. You need just follow steps in installation part of readme.

P2P requires to compile:

- boost 1.68+
- cmake 3.13+
- compiler with C++17 support

```
$ git clone https://github.com/SychevS/p2p.git
$ cd p2p
$ git submodule update --init --recursive
$ mkdir build
$ cd build
$ cmake -DBOOST_ROOT=${BOOST_ROOT} -DCMAKE_INSTALL_PREFIX=${P2P_INSTALL_ROOT} -A x64 ..
$ cmake --build . --target install
```
After that you will have compiled libs and header files in specified ${P2P_INSTALL_ROOT}.

**Comment by Zjek** [comment]
Hello，@SychevS！  There are some errors when I compile the project according to the method you provided.I have set the environment variables of boost.How can i fix this error？

boost:1.75.0
cmake:3.20

`cmake -DBOOST_ROOT=${BOOST_ROOT} -DCMAKE_INSTALL_PREFIX=D:\resource\p2p -A x64 ..
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
-- The CXX compiler identification is MSVC 19.28.29337.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Other Flags /W detected, replace it to avoid compiler warning to /W4
Other Flags /W detected, replace it to suppress third party warnings
-- The C compiler identification is MSVC 19.28.29337.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for unistd.h
-- Looking for unistd.h - not found
-- Looking for crc32c_value in crc32c
-- Looking for crc32c_value in crc32c - not found
-- Looking for snappy_compress in snappy
-- Looking for snappy_compress in snappy - not found
-- Looking for malloc in tcmalloc
-- Looking for malloc in tcmalloc - not found
-- Looking for fdatasync
-- Looking for fdatasync - not found
-- Looking for F_FULLFSYNC
-- Looking for F_FULLFSYNC - not found
-- Looking for O_CLOEXEC
-- Looking for O_CLOEXEC - not found
-- Performing Test HAVE_CLANG_THREAD_SAFETY
-- Performing Test HAVE_CLANG_THREAD_SAFETY - Failed
-- Performing Test LEVELDB_HAVE_NO_MISSING_FIELD_INITIALIZERS
-- Performing Test LEVELDB_HAVE_NO_MISSING_FIELD_INITIALIZERS - Failed
-- Performing Test HAVE_CXX17_HAS_INCLUDE
-- Performing Test HAVE_CXX17_HAS_INCLUDE - Success
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
CMake Error at D:/resource/cmake-3.20.0-rc2-windows-x86_64/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Boost (missing: system) (found suitable version "1.75.0",
  minimum required is "1.66")
Call Stack (most recent call first):
  D:/resource/cmake-3.20.0-rc2-windows-x86_64/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  D:/resource/cmake-3.20.0-rc2-windows-x86_64/share/cmake-3.20/Modules/FindBoost.cmake:2344 (find_package_handle_standard_args)
  CMakeLists.txt:64 (find_package)


-- Configuring incomplete, errors occurred!
See also "D:/qt_code/p2p/build/CMakeFiles/CMakeOutput.log".
See also "D:/qt_code/p2p/build/CMakeFiles/CMakeError.log".
`
Thanks!

**Comment by SychevS** [comment]
It seems that cmake cannot find boost system library. Try to add path to boost libraries to cmake command using BOOST_LIBRARYDIR like this:
`$ cmake -DBOOST_ROOT=${BOOST_ROOT} -DBOOST_LIBRARYDIR=${PATH_TO_BOOST_LIBS} -DCMAKE_INSTALL_PREFIX=${P2P_INSTALL_ROOT} -A x64 ..`

**Comment by Zjek** [comment]
It didn't solve the problem.I guess the mistake is because here.

--Looking for unistd.h - not found
-- Looking for crc32c_value in crc32c - not found
-- Looking for snappy_compress in snappy - not found
-- Looking for malloc in tcmalloc - not found
-- Looking for fdatasync - not found
-- Looking for F_FULLFSYNC - not found
-- Performing Test LEVELDB_HAVE_NO_MISSING_FIELD_INITIALIZERS - Failed
-- Looking for pthread.h - not found

They are the library files of Linux system.Is it a problem with my system environment？

**Comment by Zjek** [comment]
It didn't solve the problem.I guess the mistake is because here.

--Looking for unistd.h - not found
-- Looking for crc32c_value in crc32c - not found
-- Looking for snappy_compress in snappy - not found
-- Looking for malloc in tcmalloc - not found
-- Looking for fdatasync - not found
-- Looking for F_FULLFSYNC - not found
-- Performing Test LEVELDB_HAVE_NO_MISSING_FIELD_INITIALIZERS - Failed
-- Looking for pthread.h - not found

They are the library files of Linux system.Is it a problem with my system environment？

**Comment by Zjek** [comment]
I solved the problem.
Thanks！
