### ISSUE TITLE
How to start?

### ISSUE THREAD

**Issue by Zjek** [SychevS/p2p#2]
Hello!

I dont know how to start.Do you have an example or a detailed manual? Can you share it with me?

Thanks!

**Comment by SychevS** [comment]
Hello, @Zjek!

Unfortunately for now we have only this readme: https://github.com/SychevS/p2p/blob/master/README.md
Also interface can be founded here: https://github.com/SychevS/p2p/blob/master/include/p2p_network.h

If you wish you can submit a pull request with more detailed manual.
